
############################# Main Menu ########################
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Category"
url = "categories/"
weight = 3

[[main]]
name = "Tags"
url = "tags/"
weight = 4

############################# Footer Menu ########################
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Authors"
url = "author/"
weight = 2

[[footer]]
name = "Privacy"
url = "privacy/"
weight = 3

[[footer]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 4
